config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :recipe_foods
    end
  devise_for :users
  resources :homes
  resources :foods
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :shopping_lists
    resources :recipe_foods
    end
  get '/public_recipes', to: 'recipes#public'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#public"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  belongs_to :user

  validates :name, presence: true

  def count_total_price
    total = 0
    recipe_foods.each do |rf|
      food = Food.find(rf.food_id)
      total += food.price
    end
    total
  end

  def count_total_food_items
    recipe_foods.sum('quantity')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:public]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])
    @public = @recipe.public ? false : true
    Recipe.update(@recipe.id, public: @public)
    redirect_to recipe_path
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public
    @recipes = Recipe.where(public: true).order('created_at DESC')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :cooking_time, :preparation_time, :public, :description)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_modal.html.erb
<div id="myModal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
          <span class="close">&times;</span>
        </div>
        <div class="modal-body">
        </div>
      </div>
  </div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>


<div id="recipes" class="container">
  <% @recipes.each_with_index do |recipe, idx| %>
  
    <div class="row border border-dark border-4 p-5 mt-5 fs-2">
      <%= link_to recipe_path(recipe.id), :remote => true, class: 'text-decoration-none text-dark' do %>
      <div class="col-4">
        <h2 class="pb-2">Recipe <%= idx+1 %></h2>
        <%= link_to 'Remove', recipe_path(id: recipe.id), data: { turbo_method: :delete, class: 'fs-3' } %>
      </div>
      <div class="col-4 fs-4">
        <p><%= recipe.description %></p>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <section class="body container">  
  <h1 class="d-flex justify-content-center mt-3">Add a new Recipe</h1>

  <%= form_with model: @recipe do |f| %>

  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= f.label :cooking_time %>
    <%= f.text_field :cooking_time, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= f.label :preparation_time %>
    <%= f.text_field :preparation_time, class: "form-control"%>
  </div>

  <div class="mb-3">
    <%= f.check_box :public%>
    <%= f.label :public %>
  </div>

  <div class="mb-3">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control"%>
  </div>

    <div class="mb-3 mt-5 d-flex justify-content-center">
     <%= f.submit class: "btn btn-primary" %>
     </div>

    <% end %>
    </section>

  </body>
</html>

app/views/recipes/public.html.erb
<h1 class="text-center text-primary py-2">Welcome to Recipe App</h1>

<div class="container text-center">
  <h2>
    <i>Recipe app keeps track of all your recipes, ingredients, and inventory. 
    It will allow you to save ingredients, keep track of what you have, create recipes, 
    and generate a shopping list based on what you have and what you are missing from a 
    recipe. Also, since sharing recipes is an important part of cooking the app should 
    allow you to make them public so anyone can access them.</i>
  </h2>
  <h3 class="text-info py-2">To use the app you need to create an account and log in.</h3>

 
</div>
<div class='px-5'>
  <h2 class="text-center pt-5 text-primary">Public Recipes for some users</h2>
  <div class='container'>
  <% if @recipes.length > 0 %>
    <% @recipes.each do |recipe| %>
        <div class='row my-3 border card border-4 p-3'>
          <%= link_to recipe_path(recipe ) do %>
            <div class='col'>
              <h2><%= recipe.name %></h2>
              <h4>By: <%= recipe.user.name %></h4>
            </div>

            <div class='col-8 fs-5'>
              <p>Total food items: <%= recipe.count_total_food_items %></p>
              <p>Total price: $<%= recipe.count_total_price %></p>
            </div>
          <% end %>
        </div>
    <% end %>
  <% else %>
  <h2 class="text-center card py-2 text-info">No public recipes yet</h2>
<% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<section class="body container">
    <div class="heading d-flex justify-content-center mt-3 mb-4">
      <h1><%=@recipe.name%></h1>
    </div>

    <div class="grid">

      <div>
        <p class="fs-3 mb-4 text-primary">Preparation Time: <%=@recipe.preparation_time%></p>
        <p class="fs-3 mb-4 text-primary">Cooking Time: <%=@recipe.cooking_time%></p>
        <p class="fs-3 mb-4">Steps go here...</p>
      </div>
      <h3>
       <%if @recipe.public == false%>
          <div class="form-check form-switch">
            <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
          </div>
        <%else%>
          <div class="form-check form-switch">
            <label class="form-check-label" for="flexSwitchCheckChecked">Public</label>  
            <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
          </div>
        <%end%>
       </h3>

    </div>

    <div class="grid">
      <%= link_to new_recipe_recipe_food_path(@recipe.id), :remote => true do %>
        <input type="button" class="btn btn-primary" value="Generate shopping list">

      <%end%>
      <%= link_to new_recipe_recipe_food_path(@recipe.id), :remote => true do %>
        <input type="button" class="btn btn-primary" value="Add Ingredients">

      <%end%>

    </div>

      <hr>

          <div class="table">
      <table class="table table-bordered">
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Action</th>
      </tr>

      <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%=Food.find(recipe_food.food_id).name%></td>
        <td><%=recipe_food.quantity%> <%=Food.find(recipe_food.food_id).measurement_unit%></td>
         <td> $<%=RecipeFood.value(recipe_food.id)%></td>
        <td>
        <div class="flex-btn">
          <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_food.recipe_id,recipe_food.id), html: {'data-turbo' => "false"}, :method => :get, class: "btn btn-success" %>
          <%= link_to "Delete", recipe_recipe_food_path(recipe_food.recipe_id,recipe_food.id), html: {'data-turbo' => "false"}, :method => :delete, class: "btn btn-danger" %>
        </div>
       </td>
      </tr>
      <%end%>

      </table>
    </div>

    </section>

  </body>