config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :recipe_foods
    end
  devise_for :users
  resources :homes
  resources :foods
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :shopping_lists
    resources :recipe_foods
    end
  get '/public_recipes', to: 'recipes#public'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#public"
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
  belongs_to :user
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">

  <div class="form-group">
    <%= form.label :Name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Measurement_unit, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :measurement_unit, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Unit_price, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="mt-5 d-flex justify-content-center">
  <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<%# notification %>
<p style="color: green"><%= notice %></p>

<%# display all foods %>

<div id="foods" class="container">
<div class="d-flex justify-content-end">
<%= link_to "Add food", new_food_path, class:'btn btn-success' %>
</div>
    <table class="table table-bordered table-striped table-success mt-3">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Measurement Unit</th>
          <th scope="col">Unit Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$ <%= food.price %></td>
          <td>  <%= link_to 'Delete', food_path(id: food.id), data: { turbo_method: :delete } %></td>
        </tr> 
      <% end %>
      </tbody>
    </table>
</div>

app/views/foods/new.html.erb
<div class="container">
<div class="d-flex justify-content-center mt-3">
<h1>New food</h1>
</div>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path, class:'btn btn-primary' %>
</div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>