config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :recipe_foods
    end
  devise_for :users
  resources :homes
  resources :foods
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :shopping_lists
    resources :recipe_foods
    end
  get '/public_recipes', to: 'recipes#public'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#public"
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @current_user = current_user
    @inventories = Inventory.where(user_id: @current_user.id)
  end

  def show
    @current_user = current_user

    @inventory = @current_user.inventories.find(params[:id])
    @inventory_foods = @inventory.inventory_foods.all
    @already_inside = @inventory_foods.pluck(:food_id)

    @food_options = Food.where.not(id: @already_inside)
  end

  def create
    @inventory = Inventory.new
    user = current_user
    name = params[:name]
    @inventory.name = name
    @inventory.user_id = user.id
    @inventory.user_id

    redirect_to inventories_path if @inventory.save
  end

  def add
    @current_user = current_user
    @inventory = @current_user.inventories.find(params[:inventory_id])
    if can? :update, @inventory
      inv_food = InventoryFood.new
      inv_food.inventory = @inventory
      inv_food.food = Food.find(params[:food])
      inv_food.quantity = params[:quantity]
      redirect_to(request.env['HTTP_REFERER']) if inv_food.save
    else
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def remove
    @inventory = current_user.inventories.find(params[:inventory_id])
    if can? :update, @inventory
      @current_user = current_user
      inv_food = InventoryFood.find(params[:inv_fod_id])
      redirect_to(request.env['HTTP_REFERER']) if inv_food.destroy
    else
      redirect_to(request.env['HTTP_REFERER'])
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    if (can? :destroy, @inventory) && !@inventory.nil?
      @inventory.inventory_foods.each do |inventory_food|
        InventoryFood.delete_by(id: inventory_food.id)
      end
      @inventory.destroy
      redirect_to(request.env['HTTP_REFERER'], notice: 'Inventory deleted succesfully')
    else
      redirect_to(request.env['HTTP_REFERER'], notice: 'Not Access')
    end
  end

  # rubocop:disable all
  def compare
    @result = []
    @amount = 0
    @total = 0
    @current_user = current_user
    @inventory = @current_user.inventories.find(params[:inventory_id])
    @recipe = Recipe.find(params[:recipes_id])
    if (can? :read, @recipe) && !@inventory.nil?
      @recipe.recipe_foods.each do |recipe_food|
        inventory_food = @inventory.inventory_foods.find_by(food_id: recipe_food.food.id)
        if !inventory_food.nil? && inventory_food.quantity < recipe_food.quantity

          hash = {}
          @amount += 1
          hash['name'] = recipe_food.food.name
          hash['quantity'] = recipe_food.quantity - inventory_food.quantity
          hash['unit'] = recipe_food.food.measurement_unit
          hash['price'] = hash['quantity'] * recipe_food.food.price
          @total += hash['price']
          @result.push(hash)
        elsif inventory_food.nil?
          hash = {}
          @amount += 1
          hash['name'] = recipe_food.food.name
          hash['quantity'] = recipe_food.quantity
          hash['unit'] = recipe_food.food.measurement_unit
          hash['price'] = hash['quantity'] * recipe_food.food.price
          @total += hash['price']
          @result.push(hash)
        end
      end
    else
      redirect_to(request.env['HTTP_REFERER'], notice: 'Not Access')
    end
  end
  # rubocop:enable all
end

app/controllers/inventory_controller.rb
class InventoryController < ActionController::Base
  def index
    if current_user.nil?
      redirect_to new_user_session_path
    else
      @user = current_user
      @inventories = @user.inventories.all
    end
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def new
    @user = current_user
    @inventory = @user.inventories.new
  end

  def create
    @user = current_user
    # recipe = @user.recipes.new(iventory_params)
    respond_to do |format|
      format.html do
        if iventory.save
          redirect_to iventory_path(iventory)
          flash[:success] = 'Iventory was created!'
        else
          flash.now[:error] = 'Error: Recipe could not be created'
          render :new
        end
      end
    end
  end

  def destroy
    @user = current_user
    @iventories = @user.iventories.find(params[:id])
    @iventory.destroy
    redirect_to iventory_path
    flash[:success] = 'Iventory was deleted!'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
end

app/views/inventory/index.html.erb
<section class="body">

    <div class="add-btn">
      <%= link_to 'recipes/new', :remote => true do %>
      <input type="button" class="btn btn-primary" value="Add inventories">
      <% end %>
    </div>
      <% @inventory.each do |inventory| %>
     

        <div class= "inventory-border">
          <div>
           <%= link_to inventory_path(inventory.id), :remote => true do %>
            <h2><%=inventory.name%></h2>
            <% end %>
            <%= button_to "Delete", recipe_path(inventory.id), html: {'data-turbo' => "false"}, :method => :delete, class: "btn btn-danger" %>
          </div>
          <h3><%=inventory.description%></h3>
        </div>
        
      
      <% end %>

</section>

app/views/inventory/new.html.erb
section class="add-food">  
  <h1>Add a new Food</h1>
  <%= form_with model: @food do |f| %>
  <div class="food-c">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, class: "food-text"%>
  </div>
  <div class="food-c">
    <%= f.label :measurement_unit %>
    <%= f.text_field :measurement_unit, required: true, class: "food-text"%>
  </div>
  <div class="food-c">
    <%= f.label :price %>
    <%= f.number_field :price, required: true, min: 1, class: "food-text"%>
  </div>
  <div class="food-c">
    <%= f.submit class: "submit-button" %>
  </div>
  <% end %>
</section>

app/views/inventory/show.html.erb
<section class="body">
    <div class="heading">
      <h1><%=@inventory.name%></h1>
    </div>


    <div class="grid">
        
      <%= link_to new_inventory_inventory_food_path(@inventory.id), :remote => true do %>
        <input type="button" class="btn btn-primary" value="Add Food">
     
      <%end%>

    </div>

      <hr>

          <div class="table">
      <table class="table table-bordered">
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Action</th>
      </tr>

      <% @recipe.recipeFoods.each do |recipe_food| %>
      <tr>
        <td><%=Food.find(recipe_food.food_id).name%></td>
        <td><%=recipe_food.quantity%> <%=Food.find(recipe_food.food_id).measurement_unit%></td>
        <td> $<%=RecipeFood.value(recipe_food.id)%></td>
        <td>
        <div class="flex-btn">
          <%= button_to "Modify", edit_recipe_recipe_food_path(recipe_food.recipe_id,recipe_food.id), html: {'data-turbo' => "false"}, :method => :get, class: "btn btn-success" %>
          <%= button_to "Delete", recipe_recipe_food_path(recipe_food.recipe_id,recipe_food.id), html: {'data-turbo' => "false"}, :method => :delete, class: "btn btn-danger" %>
        </div>
       </td>
      </tr>
      <%end%>
      
      </table>
    </div>
    
</section>