config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :recipe_foods
    end
  devise_for :users
  resources :homes
  resources :foods
  resources :recipes, only: [:index, :new, :show, :destroy, :create] do
    resources :shopping_lists
    resources :recipe_foods
    end
  get '/public_recipes', to: 'recipes#public'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#public"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    cannot :read, :inventories
    cannot :read, :recipes, is_public: false

    return unless user.present?

    can %i[read update destroy create], Recipe, user: user
    can %i[read update destroy create], Food, user: user
    can %i[read update destroy create], Inventory, user: user

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
  belongs_to :user
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  belongs_to :user

  validates :name, presence: true

  def count_total_price
    total = 0
    recipe_foods.each do |rf|
      food = Food.find(rf.food_id)
      total += food.price
    end
    total
  end

  def count_total_food_items
    recipe_foods.sum('quantity')
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  def self.value(id)
    recipe_food = RecipeFood.find(id)
    food = recipe_food.food
    food.price * recipe_food.quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :inventories, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/general_controller.rb
class GeneralController < ActionController::Base
  def index
    @user = current_user
    @recipe = Recipe.where(user_id: @user.id)
    @recipe_foods = RecipeFood.all
    @foods = Food.where(user_id: @user.id)
    @recipes = @user.recipes
    @total = @recipes.map { |x| Recipe.total_value(x.id) }.reduce(:+)
    @food_count = 0
    @recipes.each do |recipe|
      recipe_foods = recipe.recipeFoods
      recipe_foods.each do |_food|
        @food_count += 1
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes or /homes.json
  def index
    render
  end
end

app/controllers/public_controller.rb
class PublicController < ActionController::Base
  def index
    @recipes = Recipe.includes(:recipe_foods).where(public: true).order('created_at DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <div class="container-fluid">
        <a class="navbar-brand fs-3" href="/">Recipe App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav fs-5">
                <li class="nav-item">
                    <%= link_to 'Public Recipes', public_recipes_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'My Recipes', recipes_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Foods', foods_path, class: 'nav-link' %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto fs-5 gap-3">
                <% #  if user is signed in, show sign out link %>
                <% if user_signed_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle disabled" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Welcome, <%= current_user.name %>
                    </a>
                    <div class="dropdown-menu bg-danger d-flex justify-content-center" aria-labelledby="navbarDropdownMenuLink">
                        <%= link_to 'Sign Out', destroy_user_session_path, class: 'btn btn-danger', data: { turbo_method: :delete } %>
                    </div>
                </li>
                    
                <% # if user is not signed in, show sign in link %>
                <% else %>
                    <li class="nav-item">
                        <%= link_to 'Sign In', new_user_session_path, class: 'nav-link btn btn-primary' %>
                    </li>
                <% end %>
            </ul>
        </div>
        </div>
    </nav>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/foods">Recipe App</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="navbar-collapse collapse show" id="navbarColor01" style="">
    <%= link_to "Home", root_path, class: "nav-link" %>
    <%= link_to "Foods", foods_path, class: "nav-link" %>
    <%= link_to "Recipes", recipes_path, class: "nav-link" %>
    <%= link_to "Public Recipes", public_index_path, class: "nav-link" %>
    <%= link_to "Inventory", inventories_path, class: "nav-link" %>
     <ul class="navbar-user" >
        <% if user_signed_in? %>
          <li>
            Hi, <%= current_user.name%>
          </li>
          <li>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "log-button" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Log in', new_user_session_path, class: "log-button" %>
          </li>  
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/nav' %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/popup/popup.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="modal_content">
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/popup/popup_content.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= post.title %></h4>
</div>
<div class="modal-body">
  <%= @inventories%>
</div>

app/views/popup/show_modal.js.erb
$('#modal_content').html("<%= j render 'popup_content', popup: @inventories %>");
$("#myModal").modal('show');